global:
  imagePullSecrets:
    - name: "ces-container-registries"
  networkPolicies:
    enabled: true
manager:
  image:
    registry: docker.io
    repository: cloudogu/k8s-debug-mode-operator
    tag: 1.0.1
  imagePullPolicy: Always
  env:
    logLevel: debug
    stage: production
    helmClientTimeoutMins: "15"
    rollbackReleaseTimeoutMins: "15"
    healthSyncIntervalMins: "2"
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  replicas: 1
