# The k8s-debug-mode-operator must be abel to install all components using Helm.
# Since those components contain all kinds of resources
# the k8s-debug-mode-operator needs permissions to manage all these resources.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-debug-mode-operator.name" . }}-manager-role
  labels:
    {{- include "k8s-debug-mode-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - update
      - create
      - delete
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - debugmodes
      - debugmodes/status
    verbs:
      - '*'
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - dogus
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-debug-mode-operator.name" . }}-manager-rolebinding
  labels:
    {{- include "k8s-debug-mode-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "k8s-debug-mode-operator.name" . }}-manager-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "k8s-debug-mode-operator.name" . }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'
